class ApiKeys{
  //test mode secret key
  static String secretKey='sk_test_51P9UxPBJPGZ5kdZrffiGW6YKtIYyZB3gKAbOC9RoRxdW8vZelXvXa5lR6QBTuROPzoluq577xoo1GmaG1AySDIgH00z9J61jMq';
static String publishableKey='pk_test_51P9UxPBJPGZ5kdZruupuwJTkWORELdcewssPuOxgmzt7lMM0LVDhxetWoxraRatWYTUdUvKnlIbZrg32J2cypdcg00UgBtU2dQ';
}

